# E.g.
# docker compose -f ./database/compose.yml up

name: floto-db

services:
  floto-db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    container_name: cosmos-emulator
    ports:
      - 8081:8081
      - 1234:1234
    environment:
      PROTOCOL: "http"
      GATEWAY_PUBLIC_ENDPOINT: "*"
      LOG_LEVEL: "warn"
      ENABLE_TELEMETRY: "false"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/alive" ]
      interval: 2m
      timeout: 10s
      retries: 1
      start_period: 10s
      start_interval: 1s
